# Generated by Django 5.0.7 on 2024-08-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='адрес')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/photo')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='дата создания')),
                ('publication', models.BooleanField(verbose_name='признк публикации')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='счетчик просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
