# Generated by Django 5.0.7 on 2024-08-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
