# Generated by Django 4.2.2 on 2024-09-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_version_owner_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["pk"],
                "permissions": [
                    ("can_change_publicate", "can change publicate pr"),
                    (
                        "can_change_description_product",
                        "can change publication product",
                    ),
                    ("can_change_category_product", "can change category product"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_publicate",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
